---
env:
  browser: true
  commonjs: true
  es6: true
  node: true
  jest: true
extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:react/recommended
  - plugin:jsx-a11y/recommended
  - prettier
  - prettier/react
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  sourceType: "module"
  ecmaVersion: 2020
  ecmaFeatures:
    jsx: true
plugins:
  - import
  - jest
  - react
  - react-hooks
settings:
  react:
    version: detect
  import/resolver:
    alias:
      map:
        - - pages
          - "./src/pages"
        - - components
          - "./src/components"
        - - hooks
          - "./src/hooks"
        - - styles
          - "./src/styles"
        - - utils
          - "./src/utils"
      extensions:
        - ".js"
        - ".jsx"
